insert into public.languages (code, english_name, native_name, hello_example)
values
  ('en', 'English', 'English', 'Hello'),
  ('th', 'Thai', 'ไทย', 'สวัสดี'),
  ('he', 'Hebrew', 'עברית', 'שלום'),
  ('ja', 'Japanese', '日本語', 'こんにちは'),
  ('ko', 'Korean', '한국어', '안녕하세요'),
  ('zh-CN', 'Chinese (Simplified)', '中文（简体）', '你好'),
  ('zh-TW', 'Chinese (Traditional)', '中文（繁體）', '你好'),
  ('es', 'Spanish', 'Español', 'Hola'),
  ('fr', 'French', 'Français', 'Bonjour'),
  ('de', 'German', 'Deutsch', 'Hallo'),
  ('it', 'Italian', 'Italiano', 'Ciao'),
  ('pt', 'Portuguese', 'Português', 'Olá'),
  ('ru', 'Russian', 'Русский', 'Привет'),
  ('ar', 'Arabic', 'العربية', 'مرحباً'),
  ('hi', 'Hindi', 'हिन्दी', 'नमस्ते'),
  ('vi', 'Vietnamese', 'Tiếng Việt', 'Xin chào'),
  ('id', 'Indonesian', 'Bahasa Indonesia', 'Halo'),
  ('tl', 'Filipino (Tagalog)', 'Filipino', 'Kamusta'),
  ('tr', 'Turkish', 'Türkçe', 'Merhaba'),
  ('nl', 'Dutch', 'Nederlands', 'Hallo'),
  ('pl', 'Polish', 'Polski', 'Cześć'),
  ('sv', 'Swedish', 'Svenska', 'Hej'),
  ('da', 'Danish', 'Dansk', 'Hej'),
  ('no', 'Norwegian', 'Norsk', 'Hei'),
  ('fi', 'Finnish', 'Suomi', 'Hei'),
  ('el', 'Greek', 'Ελληνικά', 'Γειά σου'),
  ('cs', 'Czech', 'Čeština', 'Ahoj'),
  ('hu', 'Hungarian', 'Magyar', 'Helló'),
  ('ro', 'Romanian', 'Română', 'Salut'),
  ('bg', 'Bulgarian', 'Български', 'Здравей'),
  ('uk', 'Ukrainian', 'Українська', 'Привіт'),
  ('sr', 'Serbian', 'Српски', 'Здраво'),
  ('hr', 'Croatian', 'Hrvatski', 'Bok'),
  ('sk', 'Slovak', 'Slovenčina', 'Ahoj'),
  ('sl', 'Slovenian', 'Slovenščina', 'Živjo'),
  ('lt', 'Lithuanian', 'Lietuvių', 'Labas'),
  ('lv', 'Latvian', 'Latviešu', 'Sveiki'),
  ('et', 'Estonian', 'Eesti', 'Tere'),
  ('sq', 'Albanian', 'Shqip', 'Përshëndetje'),
  ('bs', 'Bosnian', 'Bosanski', 'Zdravo'),
  ('mk', 'Macedonian', 'Македонски', 'Здраво'),
  ('hy', 'Armenian', 'Հայերեն', 'Բարև'),
  ('ka', 'Georgian', 'ქართული', 'გამარჯობა'),
  ('fa', 'Persian (Farsi)', 'فارسی', 'سلام'),
  ('ur', 'Urdu', 'اردو', 'سلام'),
  ('bn', 'Bengali', 'বাংলা', 'হ্যালো'),
  ('ta', 'Tamil', 'தமிழ்', 'வணக்கம்'),
  ('te', 'Telugu', 'తెలుగు', 'హలో'),
  ('kn', 'Kannada', 'ಕನ್ನಡ', 'ನಮಸ್ಕಾರ'),
  ('ml', 'Malayalam', 'മലയാളം', 'നമസ്കാരം'),
  ('mr', 'Marathi', 'मराठी', 'नमस्कार'),
  ('pa', 'Punjabi', 'ਪੰਜਾਬੀ', 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ'),
  ('gu', 'Gujarati', 'ગુજરાતી', 'નમસ્તે'),
  ('si', 'Sinhala', 'සිංහල', 'හෙලෝ'),
  ('ne', 'Nepali', 'नेपाली', 'नमस्ते'),
  ('my', 'Burmese', 'မြန်မာ', 'မင်္ဂလာပါ'),
  ('km', 'Khmer', 'ខ្មែរ', 'សួស្តី'),
  ('lo', 'Lao', 'ລາວ', 'ສະບາຍດີ'),
  ('mn', 'Mongolian', 'Монгол', 'Сайн уу'),
  ('ms', 'Malay', 'Bahasa Melayu', 'Halo'),
  ('sw', 'Swahili', 'Kiswahili', 'Habari'),
  ('af', 'Afrikaans', 'Afrikaans', 'Hallo'),
  ('ha', 'Hausa', 'Hausa', 'Sannu'),
  ('yo', 'Yoruba', 'Yorùbá', 'Bawo'),
  ('ig', 'Igbo', 'Igbo', 'Ndeewo'),
  ('so', 'Somali', 'Soomaali', 'Iska warran'),
  ('zu', 'Zulu', 'isiZulu', 'Sawubona'),
  ('xh', 'Xhosa', 'isiXhosa', 'Molo'),
  ('am', 'Amharic', 'አማርኛ', 'ሰላም'),
  ('ht', 'Haitian Creole', 'Kreyòl Ayisyen', 'Bonjou'),
  ('mg', 'Malagasy', 'Malagasy', 'Manao ahoana'),
  ('mi', 'Maori', 'Māori', 'Kia ora'),
  ('sm', 'Samoan', 'Gagana Sāmoa', 'Talofa'),
  ('to', 'Tongan', 'Lea fakatonga', 'Mālō e lelei'),
  ('fj', 'Fijian', 'Vosa Vakaviti', 'Bula'),
  ('haw', 'Hawaiian', 'ʻŌlelo Hawaiʻi', 'Aloha'),
  ('is', 'Icelandic', 'Íslenska', 'Halló'),
  ('ga', 'Irish', 'Gaeilge', 'Dia dhuit'),
  ('gd', 'Scottish Gaelic', 'Gàidhlig', 'Halò'),
  ('cy', 'Welsh', 'Cymraeg', 'Helo'),
  ('eu', 'Basque', 'Euskara', 'Kaixo'),
  ('ca', 'Catalan', 'Català', 'Hola'),
  ('gl', 'Galician', 'Galego', 'Ola'),
  ('lb', 'Luxembourgish', 'Lëtzebuergesch', 'Moien'),
  ('mt', 'Maltese', 'Malti', 'Ħelow'),
  ('eo', 'Esperanto', 'Esperanto', 'Saluton'),
  ('la', 'Latin', 'Latīna', 'Salve'),
  ('ku', 'Kurdish (Kurmanji)', 'Kurdî', 'Slav'),
  ('ps', 'Pashto', 'پښتو', 'سلام'),
  ('bo', 'Tibetan', 'བོད་སྐད་', 'བཀྲ་ཤིས་བདེ་ལེགས།'),
  ('uz', 'Uzbek', 'Oʻzbekcha', 'Salom'),
  ('kk', 'Kazakh', 'Қазақ', 'Сәлем'),
  ('tk', 'Turkmen', 'Türkmençe', 'Salam'),
  ('ky', 'Kyrgyz', 'Кыргызча', 'Салам'),
  ('tg', 'Tajik', 'Тоҷикӣ', 'Салом'),
  ('be', 'Belarusian', 'Беларуская', 'Прывітанне'),
  ('se', 'Northern Sámi', 'Sámegiella', 'Bures'),
  ('jv', 'Javanese', 'ꦧꦱꦗꦮ', 'Halo'),
  ('ceb', 'Cebuano', 'Binisaya', 'Kumusta')
on conflict (code) do update
set english_name = excluded.english_name,
    native_name = excluded.native_name,
    hello_example = excluded.hello_example;
